# coding: utf-8

# flake8: noqa

"""
    Simple API

    Formacion Swagger  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: a.vivanco@scrm.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.admins_api import AdminsApi
from swagger_client.api.developers_api import DevelopersApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.item_anidado import ItemAnidado
from swagger_client.models.item_principal import ItemPrincipal
