# coding: utf-8

"""
    Simple API

    Formacion Swagger  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: a.vivanco@scrm.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.developers_api import DevelopersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDevelopersApi(unittest.TestCase):
    """DevelopersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.developers_api.DevelopersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_inventory(self):
        """Test case for search_inventory

        searches inventory  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
