# coding: utf-8

"""
    Simple API

    Formacion Swagger  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: a.vivanco@scrm.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.item_principal import ItemPrincipal  # noqa: E501
from swagger_client.rest import ApiException


class TestItemPrincipal(unittest.TestCase):
    """ItemPrincipal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemPrincipal(self):
        """Test ItemPrincipal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.item_principal.ItemPrincipal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
