---
execution:
- concurrency: 1
  hold-for: 1m
  scenario: Simple-API
scenarios:
  Simple-API:
    default-address: ${default-address}
    requests:
    - label: search_inventory
      url: ${default-path}/inventory
    - label: add_inventory
      method: POST
      url: ${default-path}/inventory
settings:
  env:
    default-address: https://virtserver.swaggerhub.com
    default-path: /MrsDaehin/PruebaJMeter/1.0.0

