# coding: utf-8

# flake8: noqa
"""
    Simple API

    Formacion Swagger  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: a.vivanco@scrm.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.item_anidado import ItemAnidado
from swagger_client.models.item_principal import ItemPrincipal
